services: 

  notebook:
    build: .
    container_name: notebook
    ports: 
      - "8888:8888"
    environment:
      PYTHONBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    volumes:
      - ./notebooks:/app
      - ./:/home 
    depends_on:
      - postgres
      - couchdb
    networks:
      - notebook_net
    
  postgres: 
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: db_postgre
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - notebook_net
  
  couchdb:
    image: couchdb:latest
    container_name: couchdb
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/var/lib/couchdb/data
    networks:
      - notebook_net
  
volumes:
  postgres_data:
  couchdb_data:

networks:
  notebook_net:
    driver: bridge